# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DWzIOCFMu7pLe7f-HPvWzhwl5RqopkXa
"""

import pandas as pd

royhat={
    "Ism":["Humoyunmirzo" ,"Jaloliddin" ,"Bunyodbek" ],
    "Familiya":["Anvarjonov" ,"Umaraliyev" ,"Mahmudov"],
    "Yoshi":["19" ,"19" ,"15"],
    "Manzili":["Qo'qon" ,"Qo'qon" ,"Marg'ilon"],
    "Jinsi":["Erkak" ,"Erkak" ,"Erkak"]

}
baza=pd.DataFrame(royhat)
print(baza)

filtr=baza[baza['Manzili'] =="Marg'ilon" ]
print(filtr)

filtr=baza[baza['Yoshi'] <="19"]
print(filtr)

titanik = pd.read_csv("/content/titanic.csv")
print(titanik)

filtr = titanik[titanik['Sex'] =='female']
print(filtr)

filtr = titanik[titanik['Age'] <=15]
print(filtr)

filtr = titanik[titanik['Ticket'] =="211536"]
print(filtr)